apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
        - containerPort: 20
          hostPort: 20
        - containerPort: 21
          hostPort: 21
        - containerPort: 22
          hostPort: 22000
spec:
  backend:
    serviceName: nginx
    servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: kube-system
data:
  22: default/nginx:22
