apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: nginx-config
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc
      volumes:
      - name: telegraf-config 
        configMap:
          name: telegraf-config-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  SSH_USER: admin
  SSH_PASS: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-file
data:
  telegraf.conf: |
    [[outputs.influxdb]]
      database = "telegraf"
      urls = ["__INFLUXDB_PORT__"]
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
