apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        env:
        - name: SSH_USERNAME
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: password
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80       default_server;
        listen [::]:80  default_server;
        return 301      https://$host$request_uri;
    }
    server {
        listen  443         ssl;
        listen  [::]:443    ssl;

        server_name           _;
        index                 index.html;
        root                  /var/www/localhost/htdocs;
        ssl_certificate       /ssl/cert.crt;
        ssl_certificate_key   /ssl/cert.key;

        location / {
            try_files $uri $uri/ =404;
        }

        location /wordpress/ {
            return 307  http://$host:5050/;
        }

        location /phpmyadmin/ {
            proxy_pass  http://$host:5000/;
        }

        location /grafana/ {
            proxy_pass          http://grafana:3000/;
            rewrite             ^/grafana/(.*) /$1 break;
            proxy_set_header    X-WEBAUTH-USER admin;
        }
    }
