apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: phpmyadmin-config
          mountPath: /var/www/localhost/htdocs/config.inc.php
          subPath: config.inc.php
        - name: phpmyadmin-persistent-storage
          mountPath: /var/www/localhost/htdocs
      volumes:
      - name: phpmyadmin-config
        configMap:
           name: phpmyadmin-config
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: ClusterIP
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 80
  selector:
    app: phpmyadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  config.inc.php: |
    <?php
    $i = 0;

    $i++;
    $cfg['Servers'][$i]['host'] = 'mysql';

    $cfg['blowfish_secret'] = 'i0ULtq/xlL:x;F7AjIYH=2I82cI[Vrly';
    $cfg['DefaultLang'] = 'en';
    $cfg['ServerDefault'] = 1;
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
    $cfg['PmaAbsoluteUri'] = '/phpmyadmin/';
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
