apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: telegraf
      containers:
      - name: influxdb
        image: influxdb-image
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-config
          mountPath: /etc/influxdb.conf
          subPath: influxdb.conf
        - name: influxdb-persistent-storage
          mountPath: /influxdata
      volumes:
      - name: influxdb-config
        configMap:
          name: influxdb-config
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  type: ClusterIP
  selector:
    app: telegraf
  ports:
  - name: telegraf
    port: 8094
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: default
data:
  influxdb.conf: |
    [meta]
      dir = "/influxdata/meta"
    [data]
      dir = "/influxdata/data"
      wal-dir = "/influxdata/wal"
    [http]
      enabled = true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx:cluster:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
rules:
  - apiGroups: [""]
    resources: 
    - persistentvolumes
    - nodes
    - deployments
    - services
    - pods
    - statefulsets
    - daemonsets
    - persistentvolumeclaims
    - ingresses
    verbs: ["get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx:telegraf
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: influx:telegraf:viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influx:telegraf
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  labels:
    app: influxdb
